DEFAULT-BAN-REASON: "Being a poo poo head"
DEFAULT-KICK-REASON: "Being a poo poo head"
DEFAULT-MUTE-REASON: "Saying naughty things!"
FORMAT-KICK-PLAYER: "You have been kicked by {0} for {1}"
FORMAT-KICK-CHAT: "{1} was kicked by {0} for '{2}'"
FORMAT-BAN-PLAYER: "You have been banned by {0} for {1}"
FORMAT-BAN-CHAT: "{1} was banned by {0} for '{2}'"
FORMAT-MUTE-PLAYER: "You have been muted by {1} for {0}"
FORMAT-MUTE-CHAT: "{1} was muted by {0} for '{2}'"
PLUGIN-PREFIX: "&8[&bSB&8]&6"