#--Messages config
DEFAULT-BAN-REASON: "Being a poo poo head"
DEFAULT-KICK-REASON: "Being a poo poo head"
DEFAULT-MUTE-REASON: "Saying naughty things!"
DEFAULT-PARDON-REASON: "Action appealed by a admin"
FORMAT-KICK-PLAYER: "You have been kicked by {0} for {1}"
FORMAT-KICK-CHAT: "{1} was kicked by {0} for '{2}'"
FORMAT-BAN-PLAYER: "You have been banned by {0} for {1}"
FORMAT-BAN-CHAT: "{1} was banned by {0} for '{2}'"
FORMAT-TEMPBAN-PLAYER: "You have been banned by {0} until {2} for {1}"
FORMAT-TEMPBAN-CHAT: "{1} was banned until {3} by {0} for '{2}'"
FORMAT-MUTE-PLAYER: "You have been muted by {1} for {0}"
FORMAT-MUTE-CHAT: "{1} was muted by {0} for '{2}'"
FORMAT-UNMUTE-PLAYER: "You have been unmuted by {1}. Reason: {0}"
FORMAT-UNMUTE-CHAT: "{1} was unmuted by {0}. Reason: '{2}'"
FORMAT-PARDON-CHAT: "{1} was pardoned by {0} for '{2}'"
PLUGIN-PREFIX: "&8[&bSB&8]&6"
# - IP Messages
FORMAT-BAN-IP-PLAYER: "Your IP, '{0}' was banned by {1} for {2}"
FORMAT-BAN-IP-CHAT: "IP Address '{0}' was banned by {1} for '{2}', affecting users {3}"
FORMAT-TEMPBAN-IP-PLAYER: "Your IP, '{0} was banned by {1} until {2} for {3}"
FORMAT-TEMPBAN-IP-CHAT: "IP Address '{0}' was temp-banned by {1} until {4} for '{2}', affecting users {3}"
FORMAT-PARDON-IP-CHAT: "IP Address '{0}' was pardoned by {1} for {2},affecting users {3}"
#--User Permission
BAN-PERMISSION: "sb.ban"
TEMPBAN-PERMISSION: "sb.tempban"
PARDON-PERMISSION: "sb.pardon"
KICK-PERMISSION: "sb.kick"
MUTE-PERMISSION: "sb.mute"
UNMUTE-PERMISSION: "sb.unmute"
PROBATE-PERMISSION: "sb.probate"
# -IP Permissions
BAN-IP-PERMISSION: "sb.ban.ip"
VIEW-PLAYER-IPS-PERMISSION: "sb.view.ipList"
TEMPBAN-IP-PERMISSION: "sb.tempban.ip"
PARDON-IP-PERMISSION: "sb.pardon.ip"
#Channel Permissions
VIEW-ADMIN-CHANNEL-PERMISSION: "sb.chat.admin"
CHAT-COLOR-PERMISSION: "sb.chat.color"
# - Server Administration
IMPORT-JSON-DATA: "sb.json.import"
VIEW-ANNOUNCEMENT-GUI: "sb.annouce.view"
#EULA
ENABLE-EULA: true
#params : %playerName% %playerUUID%
POST-EULA-COMMANDS:
  - "msg %player% Hello"
#Discord bot
ENABLE-DISCORD-BOT: false
DISCORD-BOT-TOKEN: "bread"
DISCORD-CATEGORY-TITLE: ""
DISCORD-GUILD-ID: "myid"
DISCORD-BAN-SYNCING: true
#Can be ALL or LINKED
GLOBAL-CHAT-VISIBILITY: "ALL"
LINK-COMMAND-PERMISSION: "sb.chat.link"
#WebServer
ENABLE-WEB-SERVER: false
WEBSERVER-PORT: 8080
##Uncomment the line below to manually set the webserver bind address. Use this only if you know what you're doing!
#WEBSERVER-HOST-ADDRESS: 0.0.0.0
#MySQL Connection

SQL-HOST: 'locahost'
SQL-PORT: '3306'
SQL-USERNAME: 'mysql'
SQL-PASSWORD: 'whale'
SQL-DATABASE: 'database'
ENABLE-CACHING: true
BUNGEE: false
THIS-SERVER-NAME: "Lobby"
THIS-PORT: 25599
SUB-SERVERS:
  - "localhost:25565"
  - "localhost:25566"