#--Messages config
DEFAULT-BAN-REASON: "Being a poo poo head"
DEFAULT-KICK-REASON: "Being a poo poo head"
DEFAULT-MUTE-REASON: "Saying naughty things!"
DEFAULT-PARDON-REASON: "Action appealed by a admin"
FORMAT-KICK-PLAYER: "You have been kicked by {0} for {1}"
FORMAT-KICK-CHAT: "{1} was kicked by {0} for '{2}'"
FORMAT-BAN-PLAYER: "You have been banned by {0} for {1}"
FORMAT-BAN-CHAT: "{1} was banned by {0} for '{2}'"
FORMAT-TEMPBAN-PLAYER: "You have been banned by {0} until {2} for {1}"
FORMAT-TEMPBAN-CHAT: "{1} was banned until {3} by {0} for '{2}'"
FORMAT-MUTE-PLAYER: "You have been muted by {1} for {0}"
FORMAT-MUTE-CHAT: "{1} was muted by {0} for '{2}'"
FORMAT-UNMUTE-PLAYER: "You have been unmuted by {1}. Reason: {0}"
FORMAT-UNMUTE-CHAT: "{1} was unmuted by {0}. Reason: '{2}'"
FORMAT-PARDON-CHAT: "{1} was pardoned by {0} for '{2}'"
PLUGIN-PREFIX: "&8[&bSB&8]&6"
# - IP Messages
FORMAT-BAN-IP-PLAYER: "Your IP, '{0}' was banned by {1} for {2}"
FORMAT-BAN-IP-CHAT: "IP Address '{0}' was banned by {1} for '{2}', affecting users {3}"
FORMAT-TEMPBAN-IP-PLAYER: "Your IP, '{0} was banned by {1} until {2} for {3}"
FORMAT-TEMPBAN-IP-CHAT: "IP Address '{0}' was temp-banned by {1} until {4} for '{2}', affecting users {3}"
FORMAT-PARDON-IP-CHAT: "IP Address '{0}' was pardoned by {1} affecting users {2}"
#--User Permission
BAN-PERMISSION: "sb.ban"
TEMPBAN-PERMISSION: "sb.tempban"
PARDON-PERMISSION: "sb.pardon"
KICK-PERMISSION: "sb.kick"
MUTE-PERMISSION: "sb.mute"
UNMUTE-PERMISSION: "sb.unmute"
# -IP Permissions
BAN-IP-PERMISSION: "sb.ban.ip"
VIEW-PLAYER-IPS-PERMISSION: "sb.view.ipList"
TEMPBAN-IP-PERMISSION: "sb.tempban.ip"
PARDON-IP-PERMISSION: "sb.pardon.ip"

#Channel Permissions
VIEW-ADMIN-CHANNEL-PERMISSION: "sb.chat.admin"
CHAT-COLOR-PERMISSION: "sb.chat.color"
# - Server Administration
IMPORT-JSON-DATA: "sb.json.import"
DEFAULT-CHANNEL: "global"


#Discord bot
ENABLE-DISCORD-BOT: false
